version: "3.5"

services:
  p2p:
    hostname: p2p
    container_name: p2p
    build: ./p2p
    network_mode: "host"
    depends_on:
      - broker

  broker:
    image: eclipse-mosquitto
    hostname: broker
    container_name: broker
    volumes:
      - ./mosquitto/:/mosquitto
    network_mode: "host"
