version: "3.5"

services:
  p2p:
    hostname: p2p
    container_name: p2p
    build: ./p2p
    networks:
      - default
    depends_on:
      - broker

  broker:
    image: eclipse-mosquitto
    hostname: broker
    container_name: broker
    volumes:
      - ./mosquitto/:/mosquitto
    networks:
      - default
    ports:
      - "1883:1883"

networks:
  default: