version: '3'
services:
  p2p:
    container_name: buyer-p2p
    restart: always
    build: ./p2p
    network_mode: "host"
  browser:
    container_name: buyer-browser
    restart: always
    build: ./browser
    network_mode: "host"
